"""empty message

Revision ID: 3adf720dfbdb
Revises: 4e79eb55ade4
Create Date: 2019-12-15 17:15:38.431944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adf720dfbdb'
down_revision = '4e79eb55ade4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))

    # Added by MSJ
    op.execute('UPDATE Artist SET seeking_venue = False WHERE seeking_venue IS NULL;')
    op.alter_column('Artist','seeking_venue', nullable=False)

    op.drop_column('Artist', 'seeking_talent')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
